apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumiaphonebackend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jumiaphonebackend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
  selector:
    {{- include "jumiaphonebackend.selectorLabels" . | nindent 4 }}
