apiVersion: v1
kind: Service
metadata:
  name: {{ include "jumiaphone.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jumiaphone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "jumiaphone.selectorLabels" . | nindent 4 }}
